#!/usr/bin/env ruby 

=begin

This simple script to share the current folder.

Copyright (c) 2014 Niclas Hirschfeld
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
=end

require "sinatra"

set :logging, false
set :bind, '0.0.0.0'
set :port, 1337



if ARGV.empty?
  puts "Share the current folder? [Y/n]"
  if !gets.include? "Y"
    exit
  end
  set :public_folder, Dir.pwd
else
  set :public_folder, nil
end

get '/' do
  if ARGV.empty?
    puts "show user folder content? [Y/n]"
    if gets.include? "Y"
      "<html><body><ul>#{Dir.entries(Dir.pwd).map{|e| "<li><a href=\".\/#{e}\">#{e}</a></li>"}.join('')}</ul></body></html>"
    else
      "Nop"
    end
  else
    send_file ARGV.last
  end
end